name: DEPLOY_FUNCTION_PDN

on: 
  workflow_dispatch:
    inputs:
      deploy-message:
        description: 'Tags for firebase fuction deploy'
        required: true
        default: 'main'
        
        
jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '14.x'
    - run: ls -l
      working-directory: ./functions
    - run: npm install
    - run: ls -l
    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only functions --project=default --message \"${{ github.event.inputs.deploy-message }}  - Deployed from GitHub Actions \"
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    
